id: 'lights_bedroom_2_dim'
alias: Lights Bedroom 2 Dim
initial_state: true
trigger:
  - at: "22:00:00"
    platform: time
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: state
    entity_id: person.amelia
    state: "home"
action:
  - service: light.turn_on
    data:
      entity_id: light.amelia_s_lamp
      brightness: 20
      transition: 5
mode: single